name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tofu Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read .tool-versions
        id: tool-versions
        run: |
          TOFU_VERSION=$(grep opentofu .tool-versions | awk '{print $2}')
          echo "tofu_version=$TOFU_VERSION" >> $GITHUB_OUTPUT

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.tool-versions.outputs.tofu_version }}

      - name: Initialize Tofu
        run: tofu init

      - name: Run Tests
        run: tofu test
